/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        },
        {
            "name": "tags",
            "required": false
        }
    ],
    "debugbar.queries.explain": [],
    "sanctum.csrf-cookie": [],
    "api.features.index": [
        {
            "name": "feature",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.features.update": [
        {
            "name": "feature",
            "required": true,
            "binding": "slug"
        }
    ],
    "home": [],
    "dashboard": [],
    "customers.index": [],
    "customers.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "products.index": [],
    "products.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "orders.index": [],
    "orders.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "features.index": [
        {
            "name": "feature",
            "required": true,
            "binding": "slug"
        }
    ],
    "features.update": [
        {
            "name": "feature",
            "required": true,
            "binding": "slug"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
